import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isDeepStrictEqual } from 'node:util';
import { Document, isMap, isScalar, isSeq, parse, visit } from 'yaml';
import { schemaProblem } from '../../src/lib/data/check.js';
import { slugify } from '../../src/lib/text.js';
import { today } from '../../src/lib/dates.js';

export const DATA = process.env.DATA_DIR ?? fileURLToPath(new URL('../../data/', import.meta.url));
export const stats = { devices: 0, skipped: [] };

/** Codenames that are TVs, set-top boxes or devkits, which we don't list */
export const outOfScope = new Set();

const brandAliases = {
  poco: 'xiaomi',
  redmi: 'xiaomi',
  mi: 'xiaomi',
  moto: 'motorola',
  'f-x-tec': 'fxtec',
  '10or': '10-or',
};
export const brandKey = (vendor) => brandAliases[slugify(vendor)] ?? slugify(vendor);

export const withoutBrand = (text, brand) =>
  text.trim().replace(new RegExp(`^${brand.replace(/\W/g, '\\$&')}\\s+(?=\\w)`, 'i'), '');

const read = (file) => (existsSync(file) ? parse(readFileSync(file, 'utf8')) : undefined);

const GENERATED =
  '# Generated by npm run import. Edits get overwritten, fix it at the source link instead.\n';

/** Maps nested at least flowDepth maps deep go on one line, as do lists of plain values */
function save(file, value, schema, { flowDepth = Infinity, header = '', padded = false } = {}) {
  const doc = new Document(value, { aliasDuplicateObjects: false });
  visit(doc, {
    Seq: (_, node) => void (node.flow = node.items.every(isScalar)),
    Map: (_, node, path) => {
      const depth = path.filter(isMap).length;
      node.flow =
        depth >= flowDepth && node.items.every(({ value }) => isScalar(value) || isSeq(value));
    },
  });
  const hint = `# yaml-language-server: $schema=${'../'.repeat(relative(DATA, file).split('/').length)}schema/${schema}.json\n`;
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(
    file,
    hint + header + doc.toString({ lineWidth: 0, flowCollectionPadding: padded }),
  );
}

const devicesDir = join(DATA, 'devices');
const existing = new Map();
const slugs = new Set();
const claimed = new Set();
const claim = (names) => names.forEach((name) => claimed.add(name.toLowerCase()));
const unclaimed = (names = []) =>
  [...new Set(names)].filter((name) => !claimed.has(name.toLowerCase()));

function track(entry) {
  entry.device.codenames.forEach((codename) => existing.set(codename, entry));
  claim([...entry.device.codenames, ...(entry.device.aliases ?? [])]);
  slugs.add(`${entry.brand}/${entry.device.slug ?? slugify(entry.device.name)}`);
}

if (existsSync(devicesDir)) {
  const files = readdirSync(devicesDir, { recursive: true }).filter((path) =>
    path.endsWith('.yml'),
  );
  for (const path of files) {
    const [brand, file] = path.split('/');
    track({ brand, key: file.replace('.yml', ''), device: read(join(devicesDir, path)) });
  }
}

function ensureBrand(key, name) {
  const file = join(DATA, 'brands.yml');
  const brands = read(file) ?? [];
  if (brands.some((brand) => brand.key === key)) return;
  brands.push({ key, name });
  brands.sort((a, b) => a.key.localeCompare(b.key));
  save(file, brands, 'brands');
}

const fieldOrder = 'name slug codenames aliases released soc type hardware bootloader'.split(' ');
const inOrder = (device) =>
  Object.fromEntries(fieldOrder.filter((key) => key in device).map((key) => [key, device[key]]));

const deviceFields = ({ released, soc, type, hardware }) => ({
  ...(released && { released }),
  ...(soc && { soc }),
  ...(type && type !== 'phone' && { type }),
  ...(hardware?.length && { hardware }),
});

function createDevice(brand, { name, codenames, aliases, bootloader, ...rest }) {
  const slug = slugify(name);
  const newAliases = unclaimed(aliases);
  const entry = {
    brand,
    key: codenames[0],
    device: {
      name,
      ...(slugs.has(`${brand}/${slug}`) && { slug: `${slug}-${slugify(codenames[0])}` }),
      codenames: [codenames[0], ...unclaimed(codenames.slice(1))],
      ...(newAliases.length && { aliases: newAliases }),
      ...deviceFields(rest),
      bootloader: { unlock: 'unknown', ...bootloader },
    },
  };
  track(entry);
  stats.devices++;
  return entry;
}

function fillGaps(current, { aliases, bootloader = {}, ...rest }) {
  for (const [key, value] of Object.entries(deviceFields(rest))) current[key] ??= value;
  const { unlock, notes } = bootloader;
  if (current.bootloader.unlock === 'unknown' && unlock && unlock !== 'unknown') {
    Object.assign(current.bootloader, { unlock }, notes && { notes });
  }
  const newAliases = unclaimed(aliases);
  if (newAliases.length) current.aliases = [...(current.aliases ?? []), ...newAliases];
  claim(newAliases);
}

/**
 * Finds or creates a device, only ever filling fields that are missing or unknown.
 * Returns its primary codename, or null when it's out of scope or another brand owns it
 */
export function upsertDevice(brandName, device) {
  const codename = device.codenames[0];
  if (device.type === 'skip') outOfScope.add(codename);
  if (outOfScope.has(codename)) return null;
  const brand = brandKey(brandName);
  const found = existing.get(codename);
  if (found && found.brand !== brand) {
    stats.skipped.push(
      `${codename} (${brandName} ${device.name}) clashes with ${found.brand}/${found.key}`,
    );
    return null;
  }
  ensureBrand(brand, brandName);

  const entry = found ?? createDevice(brand, device);
  const before = found && JSON.stringify(entry.device);
  if (found) fillGaps(entry.device, device);
  if (!found || JSON.stringify(entry.device) !== before) {
    save(join(devicesDir, brand, `${entry.key}.yml`), inOrder(entry.device), 'device');
  }
  return entry.key;
}

const upstreamFile = (name) => join(DATA, 'upstream', `${name}.yml`);

export const readUpstream = (name) => read(upstreamFile(name)) ?? { devices: {} };

const sortedByKey = (object) =>
  Object.fromEntries(Object.entries(object).sort(([a], [b]) => a.localeCompare(b)));

const activeCount = (devices) =>
  Object.values(devices).filter((row) => row.status === 'active').length;

/**
 * Writes upstream/<name>.yml, keeping rows that vanished as discontinued. Throws, leaving the
 * file alone, when a source suddenly returns far fewer active devices than last time
 */
export function writeUpstream(name, devices, { schema = 'upstream', force = false } = {}) {
  const previous = readUpstream(name);
  const before = previous.devices ?? {};
  const floor = Math.floor(activeCount(before) * 0.8);
  if (!force && activeCount(devices) < floor) {
    throw new Error(
      `only ${activeCount(devices)} active devices, last import had ${activeCount(before)}`,
    );
  }

  const kept = Object.entries(before).filter(([codename]) => !outOfScope.has(codename));
  const ended = kept.filter(([codename, row]) => !devices[codename] && row.status === 'active');
  const merged = sortedByKey({
    ...Object.fromEntries(kept),
    ...Object.fromEntries(
      ended.map(([codename, row]) => [codename, { ...row, status: 'discontinued' }]),
    ),
    ...devices,
  });
  const problem = schemaProblem(schema, { imported: today, devices: merged });
  if (problem) throw new Error(`bad row, ${problem}`);
  const unchanged = isDeepStrictEqual(merged, before);
  const imported = unchanged ? previous.imported : today;
  save(upstreamFile(name), { imported, devices: merged }, schema, {
    flowDepth: schema === 'stock' ? 2 : 3,
    header: GENERATED,
    padded: true,
  });
  const added = Object.keys(devices).filter((codename) => !before[codename]).length;
  return { rows: Object.keys(merged).length, added, ended: ended.length };
}
